### ISSUE TITLE
Error when click “Open in new tab”

### ISSUE THREAD

**Issue by chenmaoran** [aidan-gibson/obsidian-opener#1]
When using the right button "Open in new tab", a new blank page will be opened, refer to GIF

![87gok-iihe4](https://user-images.githubusercontent.com/46488675/224290112-7966883d-e599-49f5-974e-4a8d6356ff83.gif)

**Comment by aidan-gibson** [comment]
Thanks for the great gif! Looking into this rn.

**Comment by aidan-gibson** [comment]
Okay, this is now resolved with release 1.0.9. Please let me know if you encounter any other issues! Thanks.
