### ISSUE TITLE
Sometimes opens new empty tabs

### ISSUE THREAD

**Issue by lukemt** [aidan-gibson/obsidian-opener#14]
Sometimes it opens new empty tabs. For example if you Cmd/Ctrl-Click something. 

Or in a scenario I screen recorded below:

https://github.com/aidan-gibson/obsidian-opener/assets/3893274/e57edd0e-7733-45d7-950e-9e81cc32f444

**Comment by aidan-gibson** [comment]
Did this happen prior to the PRs? I merged without testing, I've really gotta figure out auto-tests.

Cool YAML setup btw!

**Comment by lukemt** [comment]
Yes I'm currently using the old version (I'm waiting for the release 😜) in my main vault

**Comment by lukemt** [comment]
Strangely today, I can't reproduce this anymore. Will further observe. Has anyone else had this issue yet?

**Comment by aidan-gibson** [comment]
I also cannot reproduce (version 1.0.37). Thank you again for finding bugs with this plugin!

**Comment by lukemt** [comment]
Since we can't repro this let's close the issue. I will reopen it if it were to happen again.

**Comment by lukemt** [comment]
Ok, it happened again and I found what's causing it!

Steps to reproduce:
- open a file
- pin the tab
- click on a link to another file
- file will open in a new tab as expected
- go back to the pinned tab
- click the link the the other file (that is still open) again
- boom:
- a new empty tab will open
- the other tab (that is still open) will be activated

**Comment by lukemt** [comment]
Does also happen with Obsidian Canvas, Excalidraw and potentially various other plugins that open files in new tabs using `getLeaf()`.


https://github.com/aidan-gibson/obsidian-opener/assets/3893274/c8109c54-c7d1-46f1-a929-9993126a0689
