### ISSUE TITLE
Feature Request: open other file types with default app

### ISSUE THREAD

**Issue by chenmaoran** [aidan-gibson/obsidian-opener#2]
In addition to the PDF type, whether you can support opening other file types with default app? The best can be customized through the form of configuration.

The following is my own use of the code.

![image](https://user-images.githubusercontent.com/46488675/224459104-00e5cc91-7a3f-4e9f-bf99-2e28d284e5c0.png)

**Comment by aidan-gibson** [comment]
Sure! I'm working on a fix for issue #1 this second but adding support for other file types should be trivial; might be able to patch tonight. Thanks for spotting this! I didn't realize Obsidian could deal with mp4s, etc.
