### ISSUE TITLE
Add a command to turn on/off the functionality of the plugin

### ISSUE THREAD

**Issue by calmwaves111** [aidan-gibson/obsidian-opener#20]
![image](https://github.com/aidan-gibson/obsidian-opener/assets/56907077/4092bb83-c9b5-40f2-ac38-1f38bd54a179)
Sometimes I don't need to open in a new tab for the time being, can you add a command to this option in the command panel

**Comment by lukemt** [comment]
Hhi @calmwaves111 

Great idea! How do you envision this to work? 

I can think of 4 possibilities:

1. when you call the command, it will wait for the next page switch and revert to the default behavior once. (So you call the command and click on a link afterwards for example)
2. make it only work if the curet is inside a link and navigate directly (without click). This is probably not very comfortable in preview mode though.
3. If the mouse is hovering a link, open that link directly 
4. Define a modifier key that deactivates the plugin temporarily (like the inversion I mentioned in #17)

**Comment by lukemt** [comment]
5. Merge tabs after the click: a command that closes the new tab and navigates the old tab to the new file.

**Comment by lukemt** [comment]
6. Finally maybe this is what you had in mind: A command that toggles the new tab setting (basically activating/deactivating the plugin)

**Comment by calmwaves111** [comment]
> 6. Finally maybe this is what you had in mind: A command that toggles the new tab setting (basically activating/deactivating the plugin)

yes, I just want this. In fact, I am using the other plugin [enahnced-editing ](https://github.com/obsidian-canzi/Enhanced-editing), there is a command"查看同级上方文件" and "查看同级下方文件“, it means to view the md-file above the same level, that is, the previous md-file under the same folder.  In this case, I don't need to open in a new tab, just switch within the current tab.
so I just need deactivating about the markdown-note, This plugin works fine with other file formats, I have no problem with those

**Comment by lukemt** [comment]
gotcha! this should be fairly easy to implement

**Comment by lukemt** [comment]
wait! do you mean deactivate the plugin for on tab only or entirely?

**Comment by calmwaves111** [comment]
> wait! do you mean deactivate the plugin for on tab only or entirely?🔄  ❓

my personal thought is deactivate the plugin entirely

**Comment by lukemt** [comment]
Perfect, let's do exactly that

**Comment by lukemt** [comment]
In addition a context menu entry for when you right-click a link `Open in the same tab` would be nice
