### ISSUE TITLE
Bad collaboration with third-party pulgin `Quick Explorer`.

### ISSUE THREAD

**Issue by XMB-7** [aidan-gibson/obsidian-opener#21]
When `New Tab Default` is enabled,  items would open automatically as the cursor just slides over them.

![Image_20230808_204910](https://github.com/aidan-gibson/obsidian-opener/assets/65625632/ac403f56-af2f-48af-a016-12587c0d9f99)

**Comment by lukemt** [comment]
Hi @XMB-7

I just tried to reproduce this and It worked just fine! I'm sure this was fixed for #5 and you're still on the old version. 

Use BRAT to update the opener plugin and **restart obsidian** (needed for the update)

**Comment by XMB-7** [comment]
@lukemt Thanks for the reply. 
I just found that it is related to the popular third-party plugin `Hover Editor`. When `Hover Editor` being disabled, everything just goes fine. I have no idea the problem occurs on which side, but really hoping these two plugins collaborate well.

**Comment by XMB-7** [comment]
Set the default mode to editing view in the Hover Editor configuration page, then the problem can be reproduced. I just tested it in the provided Obsidian sandbox vault.
![Image_20230809_182241](https://github.com/aidan-gibson/obsidian-opener/assets/65625632/b082a598-5da8-4c39-a50b-fffb14413549)

**Comment by lukemt** [comment]
Thanks! Will try again

**Comment by lukemt** [comment]
Ok I can reproduce this. Thanks for bringing it up. Let me try to debug it.

**Comment by lukemt** [comment]
@XMB-7 Thank you so much for spotting this! This is now fixed! Please let me know if you find any other problems!

**Comment by XMB-7** [comment]
@lukemt Really appreciate your time and effort in solving this issue. 
I just found there is also a minor issue with the collaboration between the `Opener` and `Advanced URI`, specifically refer to this issue ([see here](https://github.com/Vinzent03/obsidian-advanced-uri/issues/135)). However, I'm not sure if the relevant feature will be widely used by the community, so it may not be a high priority fix. Therefore, please feel free to address it at your convenience. Thank you.

**Comment by lukemt** [comment]
Hi @XMB-7 

I just released a new major version with a slightly new behavior.

Would you be so kind and check if the issue still persists in the new version 2.0.0?

Thank you for your help!

**Comment by XMB-7** [comment]
I tested it in the sandbox vault and was pleased to find that the issue has been resolved. Thank you for fixing it. 💕

**Comment by lukemt** [comment]
Pleased to hear this!
