### ISSUE TITLE
Repeatedly open tabs

### ISSUE THREAD

**Issue by chenmaoran** [aidan-gibson/obsidian-opener#3]
In latest version 1.0.24

![screenshots](https://user-images.githubusercontent.com/46488675/224522259-9611c323-04a2-4ff9-9ade-7476cfebff9c.gif)

**Comment by aidan-gibson** [comment]
Thank you for catching this! It looks like it's occurring on notes within folders; sorry I didn't initially see this, my vault has a flat structure. Working on a fix now! Thanks again for spotting this.

**Comment by aidan-gibson** [comment]
Fixed by 1.0.25. Please let me know if you see anything else. Thanks again!
