### ISSUE TITLE
Beautify setting page

### ISSUE THREAD

**Issue by lukemt** [aidan-gibson/obsidian-opener#30]
@aidan-gibson what are your thoughts on beautifying the settings page?

**Comment by aidan-gibson** [comment]
One thing of note is, there's an entire subgenre of plugins that are just "open this filetype in obsidian" ie https://github.com/danieltomasz/qmd-as-md-obsidian

All of those can be consolidated into our plugin! But our way of adding extensions is clunky imo.

**Comment by aidan-gibson** [comment]
OOF it looks like at some point with the updates, the "Open Inside Obsdian" feature was broken. qmd and html no longer working for me. Sorry I should've been testing more

**Comment by aidan-gibson** [comment]
Also, changing the size of the textboxes in both manual lists is an absolute disaster. This bug probably always existed and I just didn't notice until now.

**Comment by lukemt** [comment]
Hi aidan,

Thanks for the infos. Just tired changing the textbox sizes which was super funny 😆.

I don't quite understand the "open inside obsidian feature" what is the point, don't these other plugins take care of that anyways?

**Comment by lukemt** [comment]
Also it would be cool if the list textboxes would only show up when the toggle is activated (not sure if it's possible but would be neat!)
