### ISSUE TITLE
Shortcut for "Open link under cursor to the right" doesn't work

### ISSUE THREAD

**Issue by third774** [aidan-gibson/obsidian-opener#33]
Obsidian's hotkey for "Open link under cursor to the right" `⌥⌘Enter` is broken by this extension.

**Comment by lukemt** [comment]
Hi @third774,

Thanks for spotting this!

To clarify:
It works as long as the link isn't open yet, but if the link is already opened in another tab, then it switches to it. But it should open it anew in a split pane to the right. correct?

**Comment by lukemt** [comment]
Another way to break it:
- keep a new empty tab open when calling the  "Open link under cursor to the right"  command.

**Comment by lukemt** [comment]
Hi @third774 

Just released the new major version that includes the fix. It now generally allows opening one file in several tabs. For example when calling "Open in new Tab" it will not navigate to an already open one anymore.

While this is i usability change as well - sometimes you might actually want one file to be open in several tabs - I believe this will improve the overall stability and compatibility with other plugins as well.

Thanks for your feedback!
