### ISSUE TITLE
Cannot open note from canvas by "Open in new tab"

### ISSUE THREAD

**Issue by chenmaoran** [aidan-gibson/obsidian-opener#4]
![screenshots](https://user-images.githubusercontent.com/46488675/224539212-8a06bbeb-8018-483c-9cf2-b982d516f9c5.gif)

**Comment by coderlemon17** [comment]
Same issue here, I also found that when you alternatively click between a canvas file and a .md file, the canvas file will be constantly opened in a new tab.

BTW, this plugin saves my day. I really don't like the Obsidian's default behavior that keeps opening the same file in new tabs. Hope this plugin can work with the canvas view soon.

**Comment by OmniNaut** [comment]
I have also a problem with opening canvas files but it's slightly different.
When I click in the file explorer nothing happens and Obsidian freezes even. The only way out is to close Obsidian with task manager. If I look in the console it says:

Target node is NULL

Using v1.2.6 of Obsidian, v1.0.30 of the plugin, Windows 11 22H2
