### ISSUE TITLE
Daily Note in Quick Switcher

### ISSUE THREAD

**Issue by lukemt** [aidan-gibson/obsidian-opener#43]
It would be cool if one could add commands like "Open Today's Daily Note" to the native Quick Switcher. I find it a little unintuitive to use the Command Palette for these things.

Another advantage (compared to Command Palette) would be that you can add aliases to quickly access it (for example "d").

Sure you can add keyboard shortcuts, but they are scarce.

If there is one extension that could have the ability to implement this, it would be this one.
The reason is because it already patches the openFile method. All you need to do is create a note with the name of the command and Opener could call the command instead whenever the file is opened.
The other reason is that I'm the both maintaining the Plugin and possibly the only one caring about the feature :D

**Comment by aidan-gibson** [comment]
Hi Luke! This feels a bit outta scope for this plugin and I think good alternatives exist. Have you checked out https://github.com/darlal/obsidian-switcher-plus ? From there you can run commands as well. 

To open my daily note, I've set `Periodic Notes: Open daily note` to Cmd+4. obsidian-opener then does its job of switching to it if it's already open. 

I think the really good thing about this plugin is, it's primary function is portable across many different existing extensions, as modifying openFile is what is ultimately used by everything. While creating a note for new commands is a clever idea, it does feel a bit unintuitive with the existing infra. 

Let's definitely talk more if no other plugins scratch your itch for this feature though!(: It sounds like you may want to may want to make a new plugin to modify the native Quick Switcher though, if the existing ones don't work for you UX-wise. It just feels a little disjoint from this plugin; openFile should be messed with as little as possible as it isn't part of the "real" API, and if I understand you correctly, it seems like the same thing can be accomplished without messing with openFile. 

(You've been *killing* it btw, again fantastic job!)

**Comment by lukemt** [comment]
Hi @aidan-gibson,

I did try the other switchers a while back but decided to go with the native one as long as possible for a number of reasons. (Mainly: most future proof, best performance) I experimented with them on a vault with about 10,000 linked notes. 

Including this here would be the less intrusive way I can think of. It could even be hidden behind a setting/feature flag.

Anyways, have a good one!

**Comment by aidan-gibson** [comment]
@lukemt That makes sense! As long as it isn't default behavior and doesn't break anything else, absolutely feel free

**Comment by lukemt** [comment]
As this is working for atm I'm going to close the issue. 

Can be reopened when desired

**Comment by lukemt** [comment]
As this is working for atm I'm going to close the issue. 

Can be reopened when desired
