### ISSUE TITLE
"Open Inside Obsidian" broken

### ISSUE THREAD

**Issue by aidan-gibson** [aidan-gibson/obsidian-opener#44]
<img width="958" alt="image" src="https://github.com/aidan-gibson/obsidian-opener/assets/20917687/3cef4109-c02d-4cd2-9c12-b14c010809f5">

qmd and html files should open within obsidian with these settings, but no dice. This used to work, not sure when it got bricked. 

To test, add a qmd or html file to your vault and try to open it.

**Comment by aidan-gibson** [comment]
Of note: it works if selecting from left menu thingy! 
<img width="530" alt="image" src="https://github.com/aidan-gibson/obsidian-opener/assets/20917687/81fadd1e-f01a-40c6-bcba-b8cefe9b431e">
It's just when opening from quick switcher (I am also using quick switcher++) that it doesn't work.

Maybe you were actually completely on the nose with #43 (!)

**Comment by aidan-gibson** [comment]
Huh selecting from left panel thingy works on macOS but not Linux...I've gotta do a deep dive into this. Sorry my semester is starting in a week and I'm kinda slammed with prep, I will hopefully have time for this soon but have to stop for today.

**Comment by lukemt** [comment]
Ah u re right something's broken. Let me check

**Comment by lukemt** [comment]
Please fix it if you know what's going on. I can't rn

**Comment by aidan-gibson** [comment]
Gotcha no worries! I'll get to it when I can

**Comment by lukemt** [comment]
I just compared the if statement with that of version 1.0.30 from 5 months ago and it stayed exactly the same, which is kinda strange. Last time the if statement changed (logically) was here: https://github.com/aidan-gibson/obsidian-opener/commit/9f8acb9fb875eaee5b80a464382462a9aaa16d23

... which was when the feature was implemented.

I am still trying to understand the point of the feature (Open  Inside Obsidian Manual List). 

Maybe we can simply remove it?

Just tried removing it and everything worked the way I expected it to work.

**Comment by lukemt** [comment]
Ok I found the issue you were trying to fix with that feature and fixed it by checking if the file type is registered in obsidian. Therefore the Open Inside Obsidian functionality is now obsolete IMO. please check. thx

**Comment by lukemt** [comment]
I'm only using macos so no clue how linux would do

**Comment by lukemt** [comment]
Just released the new version, please check if you find any issues
