### ISSUE TITLE
Cannot hover to see note from hover editor plugin

### ISSUE THREAD

**Issue by AzulaBeLovely** [aidan-gibson/obsidian-opener#5]
Nothingislost's Hover-editor plugin no longer functions correctly while using your plugin.
The normal ctrl + hover still functions normally

I also having similar with Make.md Context sidebar view and switcher, in all cases the only thing I see is "No file is open" "Create new file (Ctrl+N)" all the info as if I open a blank tab.

Im guessing the issue is the way your plugin handles embeds

**Comment by XMB-7** [comment]
same issue here

**Comment by lukemt** [comment]
same with excalidraw embeddings (iframe)
