### ISSUE TITLE
issues on mobile (iOS)

### ISSUE THREAD

**Issue by sharik14** [aidan-gibson/obsidian-opener#6]
Thanks so much for the plugin. Works great on desktop. I just tested it on iOS and notice a few things (recognize that your comments say it is not yet tested but hopefully this helps):

- open link to a note - appears to open it within the same stack of tabs. (i.e., if I select ... > Open in new tab, it opens in a new tab which I can then close. If I just select and follow the link it keeps it in the same tab and the back <- arrow is active). I would expect to behave the same as explicit 'open in new tab'
- open link to a PDF - still requires you to be in edit mode. then you still see "follow link" hover and "open link" and "open in new tab". But these keep you in Obsidian - they do not open with the native PDF browser (or whatever the iOS equivalent would be, presumably share sheet). I would expect the share sheet.

Thanks again!!

**Comment by lukemt** [comment]
Let's add an option to enable the plugin on mobile devices and test if it works

**Comment by lukemt** [comment]
I just tested this thing on mobile (by manually altering the isDesktopOnly flag in the manifest.json of my obsidian-opener installation) and it seems to work just the way you would expect. No bugs found so far!

**Comment by lukemt** [comment]
Let's just enable this by default!
