### ISSUE TITLE
uninstallMonkeyPatch gets overwritten

### ISSUE THREAD

**Issue by lukemt** [aidan-gibson/obsidian-opener#8]
Hi,

I just had a deep look into the code and I find it really amazing!

However I found one little issue I believe:

this.uninstallMonkeyPatch is set in monkeyPatchopenFile() but then overwritten in monkeyPatchopenLinkText().

I think you need to define a this.uninstallMonkeyPatchFile and a this.uninstallMonkeyPatchLinkText and then call both onunload.

I also tested this: When I deactivate the plugin, things still open in new tabs.

Other than that this is really good work!

**Comment by aidan-gibson** [comment]
Thanks for spotting this! I'm a bit caught up in school at the moment but if you'd like to submit a PR feel free!
